/**
 * Truth-pack loaders. Numbers come from the AMD / Research JSON payloads —
 * do not invent deltas, tape rates, or make/title splits.
 *
 *   data/week6_hx_vs_ap_gaps_2026.json
 *   data/week1_accountability_pack_2026.json
 *   data/week2_tape_2026.json
 *   data/week2_tape_top25_closer_2026.json
 *   data/week3_tape_2026.json
 *   data/week3_tape_top25_closer_2026.json
 *   data/week4_tape_2026.json
 *   data/week4_tape_top25_closer_2026.json
 *   data/week5_tape_2026.json
 *   data/week5_tape_top25_closer_2026.json
 *   data/sim_free_hx2026_7.json — free export of sim_10k_2026_hx2026_7.json
 *     (make_field, proj_wins, conf_title; no win_title). Generated by scripts/generate-sim-free.mjs. The full sim
 *     (with win_title) is server/test only: ./sim-full.server.ts. Never import the
 *     full file here — this module is bundled into the public client JS.
 */
import gapsRaw from "../../../data/week6_hx_vs_ap_gaps_2026.json" with { type: "json" };
import packRaw from "../../../data/week1_accountability_pack_2026.json" with { type: "json" };
import week2TapeRaw from "../../../data/week2_tape_2026.json" with { type: "json" };
import week2Top25Raw from "../../../data/week2_tape_top25_closer_2026.json" with { type: "json" };
import week3TapeRaw from "../../../data/week3_tape_2026.json" with { type: "json" };
import week3Top25Raw from "../../../data/week3_tape_top25_closer_2026.json" with { type: "json" };
import week4TapeRaw from "../../../data/week4_tape_2026.json" with { type: "json" };
import week4Top25Raw from "../../../data/week4_tape_top25_closer_2026.json" with { type: "json" };
import week5TapeRaw from "../../../data/week5_tape_2026.json" with { type: "json" };
import week5Top25Raw from "../../../data/week5_tape_top25_closer_2026.json" with { type: "json" };
import simRaw from "../../../data/sim_free_hx2026_7.json" with { type: "json" };
import week6ApRaw from "../../../data/week6_ap_top25_2026.json" with { type: "json" };

/**
 * Research desk flags on the Week 6 ballot (Oct. 4). Missouri (AP 14 = HX 14)
 * has no gap now; Pittsburgh (AP 25 debut, HX 53) takes its slot.
 * Oklahoma State (−71) / Mississippi State (−49) lead the |delta| sort after these.
 */
export const DISAGREE_HIGHLIGHT_NAMES = [
  "Florida",
  "Oregon",
  "Houston",
  "Pittsburgh",
  "Iowa",
  "BYU",
] as const;

export type HxApGap = {
  name: string;
  ap: number;
  hx: number;
  hx_rating: number;
  delta: number;
};

export type HxApGapsFile = {
  as_of: string;
  source_ap: string;
  source_hx: string;
  poll_week?: number;
  hx_board?: string;
  note?: string;
  gaps: HxApGap[];
  hx_not_in_ap: { hx_rank: number; name: string; hx: number }[];
  ap_not_in_hx25: { ap: number; name: string; hx_rank: number }[];
};

export type Week1Tape = {
  n: number;
  su_pct: number;
  su: string;
  hx_closer_pct: number;
  hx_closer: string;
  source: string;
};

export type HxMover = {
  name: string;
  slug: string;
  hx_rank_pre: number;
  hx_rank_post: number;
  delta_hx: number;
  delta_off: number;
  delta_def: number;
  term: string;
};

export type AccountabilityPack = {
  as_of: string;
  tape: Week1Tape;
  movers_by_abs_dhx: HxMover[];
};

export type Week2Tape = {
  n: number;
  su: string;
  su_pct: number;
  hx_closer: string;
  hx_closer_pct: number;
  closer_flag: boolean;
  closer_flag_rule: string;
  vegas_closer: string;
  hx_ats: string;
  hx_ats_pct: number;
  mae_hx: number;
  mae_vegas: number;
  brier: number;
  source: string;
};

export type Week2SeasonTape = {
  label: string;
  weeks: number[];
  su: string;
  su_pct: number;
  hx_closer: string;
  hx_closer_pct: number;
  note: string;
};

export type Week2BoardFlag = {
  id: string;
  label: string;
  result: "HIT" | "MISS";
  matchup: string;
  espn_event_id: string;
  hx: string;
  vegas: string;
  final: string;
  away_score: number;
  home_score: number;
};

export type Week2TapeFile = {
  meta: {
    week: number;
    season: number;
    as_of: string;
    scope: string;
    n: number;
    hx_version: string;
    hx_policy: string;
  };
  tape: Week2Tape;
  season: Week2SeasonTape;
  board_flags: Week2BoardFlag[];
  su_misses: { n: number; matchup: string; hx_favorite: string; winner_flip_miss: boolean }[];
  winner_flip_hits: { matchup: string }[];
  games_summary: {
    n: number;
    su_hits: number;
    su_misses: number;
    hx_closer_hits: number;
    vegas_closer_hits: number;
  };
};

export type Week2Top25Tape = {
  n: number;
  su: string;
  su_pct: number;
  hx_closer: string;
  hx_closer_pct: number;
  vegas_closer: string;
  mae_hx?: number;
  mae_vegas?: number;
  source: string;
};

export type Week2Top25CutFile = {
  meta: {
    week: number;
    season: number;
    as_of: string;
    scope: string;
    n: number;
    hx_version: string;
    hx_policy: string;
    primary_cut: string;
  };
  tape: Week2Top25Tape;
  full_slate: { n: number; hx_closer: string; closer_flag: boolean };
  ap_alt: { n: number; hx_closer: string; hx_closer_pct: number };
  su_misses: { matchup: string; closer: string }[];
  hx_closer_hits: { matchup: string }[];
  vegas_closer: { matchup: string }[];
  games_summary: {
    n: number;
    su_hits: number;
    su_misses: number;
    hx_closer_hits: number;
    vegas_closer_hits: number;
  };
};

/**
 * Free-export row of the HX 2026.7 10k sim. win_title is intentionally absent —
 * it is Edge Pack / paid only and must never reach the client bundle.
 * Full row type (with win_title) lives in ./sim-full.server.ts.
 */
export type SimFreeTeam = {
  name: string;
  slug: string;
  conference: string;
  make_field: number;
  proj_wins: number;
  conf_title: number;
};

export type SimFreeFile = {
  meta: {
    n_sims: number;
    seed: number;
    as_of: string;
    as_of_tz: string;
    hx_policy: string;
    /** Present on HX 2026.6+ packs (live free board is HX 2026.7). Absent packs fall back to the hardcoded stamp. */
    hx_stamp?: string;
    /** Full-sim file this export was derived from (e.g. sim_10k_2026_hx2026_7.json). */
    source: string;
    free_export: string;
  };
  teams: SimFreeTeam[];
};

export type Week3TapeNativeFile = {
  meta: {
    as_of: string;
    week: number;
    season: number;
    scope: string;
    n_games: number;
    su: string;
    su_pct: number;
    hx_closer: string;
    hx_closer_pct: number;
    vegas_closer: string;
    ats_hx: string;
    ats_hx_pct: number;
    mae_hx: number;
    mae_vegas: number;
    brier: number;
    season_w1_w3_su: string;
    season_w1_w3_closer: string;
    season_w1_w3_su_frac: string;
    season_w1_w3_closer_frac: string;
    headline_flags: {
      closer_below_45: boolean;
      n_su_misses: number;
      n_winner_flip_hits: number;
      n_winner_flip_misses: number;
    };
  };
  su_misses: Array<{
    matchup: string;
    hx_fav: string;
    winner_flip: boolean;
    espn_event_id: string;
  }>;
  winner_flip_hits: Array<{
    matchup: string;
    hx: string;
    vegas: string;
    final: string;
    espn_event_id: string;
  }>;
  winner_flip_misses: Array<{
    matchup: string;
    hx: string;
    vegas: string;
    final: string;
    espn_event_id: string;
  }>;
  games: Array<{
    espn_event_id: string;
    away: string;
    home: string;
    away_slug: string;
    home_slug: string;
    score_away: number;
    score_home: number;
    closer: string;
    su_hit: boolean;
    hx_spread_display: string;
    vegas_details: string;
    flags: string[];
  }>;
};

export type Week3Top25NativeFile = {
  meta: {
    as_of: string;
    week: number;
    season: number;
    universe: string;
    n_games: number;
    hx_closer: string;
    hx_closer_pct: number;
    su: string;
    su_pct: number;
    full_slate_closer: string;
  };
  games: Array<{
    espn_event_id: string;
    matchup: string;
    closer: string;
    su_hit: boolean;
    away: string;
    home: string;
  }>;
};

export const hxApGaps = gapsRaw as HxApGapsFile;
export const accountabilityPack = packRaw as AccountabilityPack;
export const week2TapePack = week2TapeRaw as Week2TapeFile;
export const week2Top25Pack = week2Top25Raw as Week2Top25CutFile;
export const week3TapePack = week3TapeRaw as Week3TapeNativeFile;
export const week3Top25Pack = week3Top25Raw as Week3Top25NativeFile;

export type Week4TapeNativeFile = {
  meta: {
    as_of: string;
    week: number;
    season: number;
    scope: string;
    n_games: number;
    su: string;
    su_pct: number;
    hx_closer: string;
    hx_closer_pct: number;
    vegas_closer: string;
    ats_hx: string;
    ats_hx_pct: number;
    mae_hx: number;
    mae_vegas: number;
    brier: number;
    season_w1_w4_su: string;
    season_w1_w4_closer: string;
    season_w1_w4_su_frac: string;
    season_w1_w4_closer_frac: string;
    headline_flags: {
      closer_below_45: boolean;
      n_su_misses: number;
      n_winner_flip_hits: number;
      n_winner_flip_misses: number;
    };
  };
  su_misses: Array<{
    matchup: string;
    hx_fav: string;
    winner_flip: boolean;
    espn_event_id: string;
  }>;
  winner_flip_hits: Array<{
    matchup: string;
    hx: string;
    vegas: string;
    final: string;
    espn_event_id: string;
  }>;
  winner_flip_misses: Array<{
    matchup: string;
    hx: string;
    vegas: string;
    final: string;
    espn_event_id: string;
  }>;
  games: Array<{
    espn_event_id: string;
    away: string;
    home: string;
    away_slug: string;
    home_slug: string;
    score_away: number;
    score_home: number;
    closer: string;
    su_hit: boolean;
    hx_spread_display: string;
    vegas_details: string;
    flags: string[];
  }>;
};


export type Week5TapeNativeFile = {
  meta: {
    as_of: string;
    week: number;
    season: number;
    scope: string;
    n_games: number;
    su: string;
    su_pct: number;
    hx_closer: string;
    hx_closer_pct: number;
    vegas_closer: string;
    ats_hx: string;
    ats_hx_pct: number;
    mae_hx: number;
    mae_vegas: number;
    brier: number;
    season_w1_w5_su: string;
    season_w1_w5_closer: string;
    season_w1_w5_su_frac: string;
    season_w1_w5_closer_frac: string;
    headline_flags: {
      closer_below_45: boolean;
      n_su_misses: number;
      n_winner_flip_hits: number;
      n_winner_flip_misses: number;
    };
  };
  su_misses: Week4TapeNativeFile["su_misses"];
  winner_flip_hits: Week4TapeNativeFile["winner_flip_hits"];
  winner_flip_misses: Week4TapeNativeFile["winner_flip_misses"];
  games: Week4TapeNativeFile["games"];
};

export const week4TapePack = week4TapeRaw as Week4TapeNativeFile;
export const week4Top25Pack = week4Top25Raw as Week3Top25NativeFile;
export const week5TapePack = week5TapeRaw as Week5TapeNativeFile;
export const week5Top25Pack = week5Top25Raw as Week3Top25NativeFile;
/** Free sim export (make-field / proj_wins / conf_title). No win_title. */
export const sim10k = simRaw as SimFreeFile;

const AP_SLUG_BY_NAME = new Map(
  (week6ApRaw.teams as { school: string; slug: string }[]).flatMap((t) => {
    const names = [t.school];
    if (t.slug === "usc") names.push("USC");
    if (t.slug === "miami") names.push("Miami");
    if (t.slug === "ole-miss") names.push("Ole Miss");
    return names.map((n) => [n, t.slug] as const);
  }),
);

/** HX 2026.7 10k draws — AMD re-sim (seed 20260913). Stamp from meta.hx_stamp when present. */
export const SIM_10K_AS_OF = sim10k.meta.as_of;
export const SIM_10K_HX_STAMP = sim10k.meta.hx_stamp ?? "HX 2026.7";
export const SIM_10K_NOTE = `${SIM_10K_HX_STAMP} · 10k draws · as_of ${SIM_10K_AS_OF}`;

export type TeamRef = {
  slug: string;
  name: string;
  shortName: string;
  colorPrimary: string;
};

export type BoardGapRow = HxApGap & {
  slug: string;
  shortName: string;
  colorPrimary: string;
  highlight: boolean;
};

const HIGHLIGHT = new Set<string>(DISAGREE_HIGHLIGHT_NAMES);

export function isOdTerm(term: string): boolean {
  return /^O\/D\b/.test(term);
}

/** Display term for movers — pack stores "O/D EPA"; chrome is O/D. */
export function odTermLabel(term: string): string {
  return isOdTerm(term) ? "O/D" : term;
}

export function gapByName(name: string): HxApGap | undefined {
  return hxApGaps.gaps.find((g) => g.name === name);
}

/**
 * Recompute HX-vs-AP gaps from an AP ballot + HX ship.
 * delta = ap_rank − hx_rank (negative = HX colder than the ballot).
 * Names follow the HX ship (USC, Miami) so the board card matches live ranks.
 */
export function recomputeHxVsApGaps(
  apTeams: { rank: number; team?: string; school?: string; slug: string }[],
  hxTeams: { slug: string; name: string; hx_rank_post: number; hx_post: number }[],
): HxApGap[] {
  const hxBySlug = new Map(hxTeams.map((t) => [t.slug, t]));
  const hxByName = new Map(hxTeams.map((t) => [t.name, t]));
  const gaps: HxApGap[] = [];
  for (const ap of apTeams) {
    const hx = hxBySlug.get(ap.slug) ?? hxByName.get(ap.team ?? ap.school ?? "");
    if (!hx) continue;
    gaps.push({
      name: hx.name,
      ap: ap.rank,
      hx: hx.hx_rank_post,
      hx_rating: hx.hx_post,
      delta: ap.rank - hx.hx_rank_post,
    });
  }
  return gaps.sort((a, b) => {
    const ad = Math.abs(b.delta) - Math.abs(a.delta);
    if (ad !== 0) return ad;
    return a.ap - b.ap;
  });
}

function refForName(name: string, teams: TeamRef[]): TeamRef | undefined {
  return teams.find((t) => t.name === name || t.shortName === name);
}

/** Board card rows: highlighted five first (JSON order), then remaining by |delta|. */
export function boardDisagreementRows(teams: TeamRef[]): BoardGapRow[] {
  const rows: BoardGapRow[] = hxApGaps.gaps.map((g) => {
    const ref = refForName(g.name, teams);
    return {
      ...g,
      slug: ref?.slug ?? AP_SLUG_BY_NAME.get(g.name) ?? slugGuess(g.name),
      shortName: ref?.shortName ?? g.name,
      colorPrimary: ref?.colorPrimary ?? "#8c8c86",
      highlight: HIGHLIGHT.has(g.name),
    };
  });
  const flagged = DISAGREE_HIGHLIGHT_NAMES.map((name) => rows.find((r) => r.name === name)).filter(
    (r): r is BoardGapRow => r != null,
  );
  const rest = rows
    .filter((r) => !r.highlight)
    .sort((a, b) => Math.abs(b.delta) - Math.abs(a.delta));
  return [...flagged, ...rest];
}

function slugGuess(name: string): string {
  return name
    .normalize("NFKD")
    .replace(/[’']/g, "")
    .replace(/&/g, "and")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

export function week1Tape(): Week1Tape {
  return accountabilityPack.tape;
}

export function week2Tape(): Week2Tape {
  return week2TapePack.tape;
}

export function week2SeasonTape(): Week2SeasonTape {
  return week2TapePack.season;
}

export function week2BoardFlags(): Week2BoardFlag[] {
  return week2TapePack.board_flags;
}

export function week2Top25Tape(): Week2Top25Tape {
  return week2Top25Pack.tape;
}

function asciiLineToDisplay(line: string): string {
  return line.replace(/ -/g, " −").replace(/^-/g, "−");
}

function pctFromLabeled(raw: string): number {
  return Number.parseFloat(raw.replace("%", ""));
}

function flagId(matchup: string, result: "HIT" | "MISS"): string {
  return `${matchup.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}-winner-flip-${result.toLowerCase()}`;
}

/** Research Week 3 tape mapped onto the board chrome shape. Headline numbers only from the pack. */
export function week3Tape(): Week2Tape {
  const m = week3TapePack.meta;
  return {
    n: m.n_games,
    su: m.su,
    su_pct: m.su_pct,
    hx_closer: m.hx_closer,
    hx_closer_pct: m.hx_closer_pct,
    closer_flag: m.headline_flags.closer_below_45,
    closer_flag_rule: "<45%",
    vegas_closer: m.vegas_closer,
    hx_ats: m.ats_hx,
    hx_ats_pct: m.ats_hx_pct,
    mae_hx: m.mae_hx,
    mae_vegas: m.mae_vegas,
    brier: m.brier,
    source: "Research week3_tape_2026 · FBS–FBS n=56 · ESPN FINALs",
  };
}

export function week3SeasonTape(): Week2SeasonTape {
  const m = week3TapePack.meta;
  return {
    label: "W1–W3",
    weeks: [1, 2, 3],
    su: m.season_w1_w3_su_frac,
    su_pct: pctFromLabeled(m.season_w1_w3_su),
    hx_closer: m.season_w1_w3_closer_frac,
    hx_closer_pct: pctFromLabeled(m.season_w1_w3_closer),
    note: "Week 1–3 rollup from Research week3_tape_2026",
  };
}

export function week3BoardFlags(): Week2BoardFlag[] {
  const byEspn = new Map(week3TapePack.games.map((g) => [g.espn_event_id, g]));
  const rows: Array<{
    result: "HIT" | "MISS";
    row: (typeof week3TapePack.winner_flip_hits)[number];
  }> = [
    ...week3TapePack.winner_flip_hits.map((row) => ({ result: "HIT" as const, row })),
    ...week3TapePack.winner_flip_misses.map((row) => ({ result: "MISS" as const, row })),
  ];
  return rows.map(({ result, row }) => {
    const game = byEspn.get(row.espn_event_id);
    return {
      id: flagId(row.matchup, result),
      label: `${row.matchup} winner-flip`,
      result,
      matchup: row.matchup,
      espn_event_id: row.espn_event_id,
      hx: asciiLineToDisplay(row.hx),
      vegas: asciiLineToDisplay(row.vegas),
      final: row.final,
      away_score: game?.score_away ?? 0,
      home_score: game?.score_home ?? 0,
    };
  });
}

export function week3Top25Tape(): Week2Top25Tape {
  const m = week3Top25Pack.meta;
  const vegasN = week3Top25Pack.games.filter((g) => g.closer === "vegas").length;
  return {
    n: m.n_games,
    su: m.su,
    su_pct: m.su_pct,
    hx_closer: m.hx_closer,
    hx_closer_pct: m.hx_closer_pct,
    vegas_closer: `${vegasN}/${m.n_games}`,
    source: "Research week3_tape_top25_closer_2026 · HX Top 25 involvement n=21 · ESPN FINALs",
  };
}

/** Research Week 4 tape mapped onto the board chrome shape. Headline numbers only from the pack. */
export function week4Tape(): Week2Tape {
  const m = week4TapePack.meta;
  return {
    n: m.n_games,
    su: m.su,
    su_pct: m.su_pct,
    hx_closer: m.hx_closer,
    hx_closer_pct: m.hx_closer_pct,
    closer_flag: m.headline_flags.closer_below_45,
    closer_flag_rule: "<45%",
    vegas_closer: m.vegas_closer,
    hx_ats: m.ats_hx,
    hx_ats_pct: m.ats_hx_pct,
    mae_hx: m.mae_hx,
    mae_vegas: m.mae_vegas,
    brier: m.brier,
    source: "Research week4_tape_2026 · FBS–FBS n=57 · ESPN FINALs",
  };
}

export function week4SeasonTape(): Week2SeasonTape {
  const m = week4TapePack.meta;
  return {
    label: "W1–W4",
    weeks: [1, 2, 3, 4],
    su: m.season_w1_w4_su_frac,
    su_pct: pctFromLabeled(m.season_w1_w4_su),
    hx_closer: m.season_w1_w4_closer_frac,
    hx_closer_pct: pctFromLabeled(m.season_w1_w4_closer),
    note: "Week 1–4 rollup from Research week4_tape_2026",
  };
}

export function week4BoardFlags(): Week2BoardFlag[] {
  const byEspn = new Map(week4TapePack.games.map((g) => [g.espn_event_id, g]));
  const rows: Array<{
    result: "HIT" | "MISS";
    row: (typeof week4TapePack.winner_flip_hits)[number];
  }> = [
    ...week4TapePack.winner_flip_hits.map((row) => ({ result: "HIT" as const, row })),
    ...week4TapePack.winner_flip_misses.map((row) => ({ result: "MISS" as const, row })),
  ];
  return rows.map(({ result, row }) => {
    const game = byEspn.get(row.espn_event_id);
    return {
      id: flagId(row.matchup, result),
      label: `${row.matchup} winner-flip`,
      result,
      matchup: row.matchup,
      espn_event_id: row.espn_event_id,
      hx: asciiLineToDisplay(row.hx),
      vegas: asciiLineToDisplay(row.vegas),
      final: row.final,
      away_score: game?.score_away ?? 0,
      home_score: game?.score_home ?? 0,
    };
  });
}

export function week4Top25Tape(): Week2Top25Tape {
  const m = week4Top25Pack.meta;
  const vegasN = week4Top25Pack.games.filter((g) => g.closer === "vegas").length;
  return {
    n: m.n_games,
    su: m.su,
    su_pct: m.su_pct,
    hx_closer: m.hx_closer,
    hx_closer_pct: m.hx_closer_pct,
    vegas_closer: `${vegasN}/${m.n_games}`,
    source: "week4_tape_top25_closer_2026 · HX Top 25 involvement n=18 · HX 2026.5 ranks · ESPN FINALs",
  };
}


/** Research Week 5 tape mapped onto the board chrome shape. Headline numbers only from the pack. */
export function week5Tape(): Week2Tape {
  const m = week5TapePack.meta;
  return {
    n: m.n_games,
    su: m.su,
    su_pct: m.su_pct,
    hx_closer: m.hx_closer,
    hx_closer_pct: m.hx_closer_pct,
    closer_flag: m.headline_flags.closer_below_45,
    closer_flag_rule: "<45%",
    vegas_closer: m.vegas_closer,
    hx_ats: m.ats_hx,
    hx_ats_pct: m.ats_hx_pct,
    mae_hx: m.mae_hx,
    mae_vegas: m.mae_vegas,
    brier: m.brier,
    source: "Research week5_tape_2026 · FBS–FBS n=55 · ESPN FINALs",
  };
}

export function week5SeasonTape(): Week2SeasonTape {
  const m = week5TapePack.meta;
  return {
    label: "W1–W5",
    weeks: [1, 2, 3, 4, 5],
    su: m.season_w1_w5_su_frac,
    su_pct: pctFromLabeled(m.season_w1_w5_su),
    hx_closer: m.season_w1_w5_closer_frac,
    hx_closer_pct: pctFromLabeled(m.season_w1_w5_closer),
    note: "Week 1–5 arithmetic from Research week5_tape_2026. Not a fresh W1–W4 audit.",
  };
}

export function week5BoardFlags(): Week2BoardFlag[] {
  const byEspn = new Map(week5TapePack.games.map((g) => [g.espn_event_id, g]));
  const rows: Array<{
    result: "HIT" | "MISS";
    row: (typeof week5TapePack.winner_flip_hits)[number];
  }> = [
    ...week5TapePack.winner_flip_hits.map((row) => ({ result: "HIT" as const, row })),
    ...week5TapePack.winner_flip_misses.map((row) => ({ result: "MISS" as const, row })),
  ];
  return rows.map(({ result, row }) => {
    const game = byEspn.get(row.espn_event_id);
    return {
      id: flagId(row.matchup, result),
      label: `${row.matchup} winner-flip`,
      result,
      matchup: row.matchup,
      espn_event_id: row.espn_event_id,
      hx: asciiLineToDisplay(row.hx),
      vegas: asciiLineToDisplay(row.vegas),
      final: row.final,
      away_score: game?.score_away ?? 0,
      home_score: game?.score_home ?? 0,
    };
  });
}

export function week5Top25Tape(): Week2Top25Tape {
  const m = week5Top25Pack.meta;
  const vegasN = week5Top25Pack.games.filter((g) => g.closer === "vegas").length;
  return {
    n: m.n_games,
    su: m.su,
    su_pct: m.su_pct,
    hx_closer: m.hx_closer,
    hx_closer_pct: m.hx_closer_pct,
    vegas_closer: `${vegasN}/${m.n_games}`,
    source: "week5_tape_top25_closer_2026 · HX Top 25 involvement n=15 · HX 2026.6 pregame ranks · ESPN FINALs",
  };
}

/** Top |ΔHX| movers whose term is O/D (not a second rating). */
export function odMovers(limit = 8): HxMover[] {
  return accountabilityPack.movers_by_abs_dhx.filter((m) => isOdTerm(m.term)).slice(0, limit);
}

export function simTeamBySlug(slug: string): SimFreeTeam | undefined {
  return sim10k.teams.find((t) => t.slug === slug);
}
