/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchupRouteImport } from './routes/matchup'
import { Route as ModelRouteImport } from './routes/model'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as RecruitingRouteImport } from './routes/recruiting'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as StatesRouteImport } from './routes/states'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as TalentRouteImport } from './routes/talent'
import { Route as StoriesSlugRouteImport } from './routes/stories.$slug'
import { Route as TeamsSlugRouteImport } from './routes/teams.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchupRoute = MatchupRouteImport.update({
  id: '/matchup',
  path: '/matchup',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelRoute = ModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitingRoute = RecruitingRouteImport.update({
  id: '/recruiting',
  path: '/recruiting',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesRoute = StatesRouteImport.update({
  id: '/states',
  path: '/states',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentRoute = TalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StoriesRoute,
} as any)
const TeamsSlugRoute = TeamsSlugRouteImport.update({
  id: '/teams/$slug',
  path: '/teams/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/matchup': typeof MatchupRoute
  '/model': typeof ModelRoute
  '/rankings': typeof RankingsRoute
  '/recruiting': typeof RecruitingRoute
  '/schedule': typeof ScheduleRoute
  '/states': typeof StatesRoute
  '/stories': typeof StoriesRouteWithChildren
  '/talent': typeof TalentRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/teams/$slug': typeof TeamsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/matchup': typeof MatchupRoute
  '/model': typeof ModelRoute
  '/rankings': typeof RankingsRoute
  '/recruiting': typeof RecruitingRoute
  '/schedule': typeof ScheduleRoute
  '/states': typeof StatesRoute
  '/stories': typeof StoriesRouteWithChildren
  '/talent': typeof TalentRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/teams/$slug': typeof TeamsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/matchup': typeof MatchupRoute
  '/model': typeof ModelRoute
  '/rankings': typeof RankingsRoute
  '/recruiting': typeof RecruitingRoute
  '/schedule': typeof ScheduleRoute
  '/states': typeof StatesRoute
  '/stories': typeof StoriesRouteWithChildren
  '/talent': typeof TalentRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/teams/$slug': typeof TeamsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/matchup'
    | '/model'
    | '/rankings'
    | '/recruiting'
    | '/schedule'
    | '/states'
    | '/stories'
    | '/talent'
    | '/stories/$slug'
    | '/teams/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/matchup'
    | '/model'
    | '/rankings'
    | '/recruiting'
    | '/schedule'
    | '/states'
    | '/stories'
    | '/talent'
    | '/stories/$slug'
    | '/teams/$slug'
  id:
    | '__root__'
    | '/'
    | '/matchup'
    | '/model'
    | '/rankings'
    | '/recruiting'
    | '/schedule'
    | '/states'
    | '/stories'
    | '/talent'
    | '/stories/$slug'
    | '/teams/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MatchupRoute: typeof MatchupRoute
  ModelRoute: typeof ModelRoute
  RankingsRoute: typeof RankingsRoute
  RecruitingRoute: typeof RecruitingRoute
  ScheduleRoute: typeof ScheduleRoute
  StatesRoute: typeof StatesRoute
  StoriesRoute: typeof StoriesRouteWithChildren
  TalentRoute: typeof TalentRoute
  TeamsSlugRoute: typeof TeamsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matchup': {
      id: '/matchup'
      path: '/matchup'
      fullPath: '/matchup'
      preLoaderRoute: typeof MatchupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model': {
      id: '/model'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof ModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiting': {
      id: '/recruiting'
      path: '/recruiting'
      fullPath: '/recruiting'
      preLoaderRoute: typeof RecruitingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states': {
      id: '/states'
      path: '/states'
      fullPath: '/states'
      preLoaderRoute: typeof StatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent': {
      id: '/talent'
      path: '/talent'
      fullPath: '/talent'
      preLoaderRoute: typeof TalentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/teams/$slug': {
      id: '/teams/$slug'
      path: '/teams/$slug'
      fullPath: '/teams/$slug'
      preLoaderRoute: typeof TeamsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StoriesRouteChildren {
  StoriesSlugRoute: typeof StoriesSlugRoute
}

const StoriesRouteChildren: StoriesRouteChildren = {
  StoriesSlugRoute: StoriesSlugRoute,
}

const StoriesRouteWithChildren =
  StoriesRoute._addFileChildren(StoriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MatchupRoute: MatchupRoute,
  ModelRoute: ModelRoute,
  RankingsRoute: RankingsRoute,
  RecruitingRoute: RecruitingRoute,
  ScheduleRoute: ScheduleRoute,
  StatesRoute: StatesRoute,
  StoriesRoute: StoriesRouteWithChildren,
  TalentRoute: TalentRoute,
  TeamsSlugRoute: TeamsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
